name:
description:
branding:
  icon: 'setting'
  color: 'blue'
inputs:
  src:
    description: 'The source batch file to be compiled'
    required: true
  exe:
    description: 'The output exe application to be build'
    required: true
    default: 'bat.exe'
runs:
  using: 'composite'
  steps:
    - name: Install the converter
      run: |
        New-Item -Path "$Env:PROGRAMFILES\Bat To Exe Converter" -ItemType Directory
        curl "https://gsf-fl.softonic.com/67e/676/08af90d870c4a8f8ab91b52d4544e93ca3/Bat_To_Exe_Converter_x64.exe?Expires=1678068497&Signature=ad4abc6155d7501827e7cc6f00f79d954ea58623&url=https://bat-to-exe-converter-x64.en.softonic.com&Filename=Bat_To_Exe_Converter_x64.exe" -o "$Env:PROGRAMFILES\Bat To Exe Converter\Bat_To_Exe.exe" -k
      shell: pwsh
      if: ${{ runner.os == 'Windows' }}
    - name: Run the converter
      run: Start-Process "$Env:PROGRAMFILES\Bat To Exe Converter\Bat_To_Exe_Converter.exe" /src "$Env:INPUTS_SRC" /exe "$Env:INPUTS_EXE"
      if: ${{ runner.os == 'Windows' }}
    - name: Throw wrong OS error (if applicable)
      run: |
        Write-Output "This action only works on Windows!"
        throw "Your OS is not supported!"
        exit 1
      if: ${{ runner.os != 'Windows' }}
