name: 'BAT to EXE Action'
author: 'Minionguyjpro'
branding:
  icon: 'box'
  color: 'green'
description: 'GitHub action to convert your Windows batch files (.bat/cmd) into executables (.exe).'

inputs:
  path:
    description: 'Path to input batch files (.bat/cmd)'
    required: true
  options:
    description: 'Extra arguments/options to include. Include the slashes for them.'
    required: false
    
runs:
  using: 'node20'
  main: 'dist/index.js'
